'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Products', [{
      name: "product1",
      cost: "2000₮",
      additional_info: "additional info 1",
      unit: 5,
      brandId: 1,
      unit_type: "ш",
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: "product2",
      cost: "3000₮",
      additional_info: "additional info 2",
      unit: 5,
      brandId: 1,
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: "product3",
      cost: "3000₮",
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      additional_info: "additional info 3",
      unit: 5,
      brandId: 1,
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: "product4",
      cost: "2000₮",
      additional_info: "additional info 1",
      unit: 5,
      brandId: 1,
      unit_type: "ш",
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: "product5",
      cost: "3000₮",
      additional_info: "additional info 2",
      unit: 5,
      brandId: 1,
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: "product6",
      cost: "3000₮",
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      additional_info: "additional info 3",
      unit: 5,
      brandId: 1,
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: "product1",
      cost: "2000₮",
      additional_info: "additional info 1",
      unit: 5,
      brandId: 2,
      unit_type: "ш",
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: "product2",
      cost: "3000₮",
      additional_info: "additional info 2",
      unit: 5,
      brandId: 2,
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: "product3",
      cost: "3000₮",
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      additional_info: "additional info 3",
      unit: 5,
      brandId: 2,
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: "product4",
      cost: "2000₮",
      additional_info: "additional info 1",
      unit: 5,
      brandId: 2,
      unit_type: "ш",
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "product4",
      cost: "2000₮",
      additional_info: "additional info 1",
      unit: 5,
      brandId: 2,
      unit_type: "ш",
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: "product5",
      cost: "3000₮",
      additional_info: "additional info 2",
      unit: 5,
      brandId: 2,
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "product5",
      cost: "3000₮",
      additional_info: "additional info 2",
      unit: 5,
      brandId: 2,
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "product5",
      cost: "3000₮",
      additional_info: "additional info 2",
      unit: 5,
      brandId: 2,
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "product5",
      cost: "3000₮",
      additional_info: "additional info 2",
      unit: 5,
      brandId: 2,
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "product5",
      cost: "3000₮",
      additional_info: "additional info 2",
      unit: 5,
      brandId: 2,
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "product5",
      cost: "3000₮",
      additional_info: "additional info 2",
      unit: 5,
      brandId: 2,
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "product5",
      cost: "3000₮",
      additional_info: "additional info 2",
      unit: 5,
      brandId: 2,
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "product5",
      cost: "3000₮",
      additional_info: "additional info 2",
      unit: 5,
      brandId: 2,
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "product5",
      cost: "3000₮",
      additional_info: "additional info 2",
      unit: 5,
      brandId: 2,
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "product5",
      cost: "3000₮",
      additional_info: "additional info 2",
      unit: 5,
      brandId: 2,
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: "product6",
      cost: "3000₮",
      filepath: "uploads/2021/9/productImage-1630895865061.png",
      additional_info: "additional info 3",
      unit: 5,
      brandId: 2,
      unit_type: "ш",
      properties: JSON.stringify(
        { өнгө: "ногоон", размер: "XL" }
      ), categoryId: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  {
    "name": "product1 of 0",
    "cost": "2000₮",
    "additional_info": "product1 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product2 of 0",
    "cost": "2000₮",
    "additional_info": "product2 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product3 of 0",
    "cost": "2000₮",
    "additional_info": "product3 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product4 of 0",
    "cost": "2000₮",
    "additional_info": "product4 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product5 of 0",
    "cost": "2000₮",
    "additional_info": "product5 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product6 of 0",
    "cost": "2000₮",
    "additional_info": "product6 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product7 of 0",
    "cost": "2000₮",
    "additional_info": "product7 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product8 of 0",
    "cost": "2000₮",
    "additional_info": "product8 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product9 of 0",
    "cost": "2000₮",
    "additional_info": "product9 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product10 of 0",
    "cost": "2000₮",
    "additional_info": "product10 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product11 of 0",
    "cost": "2000₮",
    "additional_info": "product11 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product12 of 0",
    "cost": "2000₮",
    "additional_info": "product12 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product13 of 0",
    "cost": "2000₮",
    "additional_info": "product13 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product14 of 0",
    "cost": "2000₮",
    "additional_info": "product14 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product15 of 0",
    "cost": "2000₮",
    "additional_info": "product15 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product16 of 0",
    "cost": "2000₮",
    "additional_info": "product16 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product17 of 0",
    "cost": "2000₮",
    "additional_info": "product17 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product18 of 0",
    "cost": "2000₮",
    "additional_info": "product18 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product19 of 0",
    "cost": "2000₮",
    "additional_info": "product19 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product20 of 0",
    "cost": "2000₮",
    "additional_info": "product20 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product21 of 0",
    "cost": "2000₮",
    "additional_info": "product21 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product22 of 0",
    "cost": "2000₮",
    "additional_info": "product22 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product23 of 0",
    "cost": "2000₮",
    "additional_info": "product23 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product24 of 0",
    "cost": "2000₮",
    "additional_info": "product24 of 0 additional info ",
    "unit": 5,
    "brandId": 10,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 10,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product1 of 1",
    "cost": "2000₮",
    "additional_info": "product1 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product2 of 1",
    "cost": "2000₮",
    "additional_info": "product2 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product3 of 1",
    "cost": "2000₮",
    "additional_info": "product3 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product4 of 1",
    "cost": "2000₮",
    "additional_info": "product4 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product5 of 1",
    "cost": "2000₮",
    "additional_info": "product5 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product6 of 1",
    "cost": "2000₮",
    "additional_info": "product6 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product7 of 1",
    "cost": "2000₮",
    "additional_info": "product7 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product8 of 1",
    "cost": "2000₮",
    "additional_info": "product8 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product9 of 1",
    "cost": "2000₮",
    "additional_info": "product9 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product10 of 1",
    "cost": "2000₮",
    "additional_info": "product10 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product11 of 1",
    "cost": "2000₮",
    "additional_info": "product11 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product12 of 1",
    "cost": "2000₮",
    "additional_info": "product12 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product13 of 1",
    "cost": "2000₮",
    "additional_info": "product13 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product14 of 1",
    "cost": "2000₮",
    "additional_info": "product14 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product15 of 1",
    "cost": "2000₮",
    "additional_info": "product15 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product16 of 1",
    "cost": "2000₮",
    "additional_info": "product16 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product17 of 1",
    "cost": "2000₮",
    "additional_info": "product17 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product18 of 1",
    "cost": "2000₮",
    "additional_info": "product18 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product19 of 1",
    "cost": "2000₮",
    "additional_info": "product19 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product20 of 1",
    "cost": "2000₮",
    "additional_info": "product20 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product21 of 1",
    "cost": "2000₮",
    "additional_info": "product21 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product22 of 1",
    "cost": "2000₮",
    "additional_info": "product22 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product23 of 1",
    "cost": "2000₮",
    "additional_info": "product23 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product24 of 1",
    "cost": "2000₮",
    "additional_info": "product24 of 1 additional info ",
    "unit": 5,
    "brandId": 1,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 1,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product1 of 2",
    "cost": "2000₮",
    "additional_info": "product1 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product2 of 2",
    "cost": "2000₮",
    "additional_info": "product2 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product3 of 2",
    "cost": "2000₮",
    "additional_info": "product3 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product4 of 2",
    "cost": "2000₮",
    "additional_info": "product4 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product5 of 2",
    "cost": "2000₮",
    "additional_info": "product5 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product6 of 2",
    "cost": "2000₮",
    "additional_info": "product6 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product7 of 2",
    "cost": "2000₮",
    "additional_info": "product7 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product8 of 2",
    "cost": "2000₮",
    "additional_info": "product8 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product9 of 2",
    "cost": "2000₮",
    "additional_info": "product9 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product10 of 2",
    "cost": "2000₮",
    "additional_info": "product10 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product11 of 2",
    "cost": "2000₮",
    "additional_info": "product11 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product12 of 2",
    "cost": "2000₮",
    "additional_info": "product12 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product13 of 2",
    "cost": "2000₮",
    "additional_info": "product13 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product14 of 2",
    "cost": "2000₮",
    "additional_info": "product14 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product15 of 2",
    "cost": "2000₮",
    "additional_info": "product15 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product16 of 2",
    "cost": "2000₮",
    "additional_info": "product16 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product17 of 2",
    "cost": "2000₮",
    "additional_info": "product17 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product18 of 2",
    "cost": "2000₮",
    "additional_info": "product18 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product19 of 2",
    "cost": "2000₮",
    "additional_info": "product19 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product20 of 2",
    "cost": "2000₮",
    "additional_info": "product20 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product21 of 2",
    "cost": "2000₮",
    "additional_info": "product21 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product22 of 2",
    "cost": "2000₮",
    "additional_info": "product22 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product23 of 2",
    "cost": "2000₮",
    "additional_info": "product23 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product24 of 2",
    "cost": "2000₮",
    "additional_info": "product24 of 2 additional info ",
    "unit": 5,
    "brandId": 2,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 2,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product1 of 3",
    "cost": "2000₮",
    "additional_info": "product1 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product2 of 3",
    "cost": "2000₮",
    "additional_info": "product2 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product3 of 3",
    "cost": "2000₮",
    "additional_info": "product3 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product4 of 3",
    "cost": "2000₮",
    "additional_info": "product4 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product5 of 3",
    "cost": "2000₮",
    "additional_info": "product5 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product6 of 3",
    "cost": "2000₮",
    "additional_info": "product6 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product7 of 3",
    "cost": "2000₮",
    "additional_info": "product7 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product8 of 3",
    "cost": "2000₮",
    "additional_info": "product8 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product9 of 3",
    "cost": "2000₮",
    "additional_info": "product9 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product10 of 3",
    "cost": "2000₮",
    "additional_info": "product10 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product11 of 3",
    "cost": "2000₮",
    "additional_info": "product11 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product12 of 3",
    "cost": "2000₮",
    "additional_info": "product12 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product13 of 3",
    "cost": "2000₮",
    "additional_info": "product13 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product14 of 3",
    "cost": "2000₮",
    "additional_info": "product14 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product15 of 3",
    "cost": "2000₮",
    "additional_info": "product15 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product16 of 3",
    "cost": "2000₮",
    "additional_info": "product16 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product17 of 3",
    "cost": "2000₮",
    "additional_info": "product17 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product18 of 3",
    "cost": "2000₮",
    "additional_info": "product18 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product19 of 3",
    "cost": "2000₮",
    "additional_info": "product19 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product20 of 3",
    "cost": "2000₮",
    "additional_info": "product20 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product21 of 3",
    "cost": "2000₮",
    "additional_info": "product21 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product22 of 3",
    "cost": "2000₮",
    "additional_info": "product22 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product23 of 3",
    "cost": "2000₮",
    "additional_info": "product23 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product24 of 3",
    "cost": "2000₮",
    "additional_info": "product24 of 3 additional info ",
    "unit": 5,
    "brandId": 3,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 3,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product1 of 4",
    "cost": "2000₮",
    "additional_info": "product1 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product2 of 4",
    "cost": "2000₮",
    "additional_info": "product2 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product3 of 4",
    "cost": "2000₮",
    "additional_info": "product3 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product4 of 4",
    "cost": "2000₮",
    "additional_info": "product4 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product5 of 4",
    "cost": "2000₮",
    "additional_info": "product5 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product6 of 4",
    "cost": "2000₮",
    "additional_info": "product6 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product7 of 4",
    "cost": "2000₮",
    "additional_info": "product7 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product8 of 4",
    "cost": "2000₮",
    "additional_info": "product8 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product9 of 4",
    "cost": "2000₮",
    "additional_info": "product9 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product10 of 4",
    "cost": "2000₮",
    "additional_info": "product10 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product11 of 4",
    "cost": "2000₮",
    "additional_info": "product11 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product12 of 4",
    "cost": "2000₮",
    "additional_info": "product12 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product13 of 4",
    "cost": "2000₮",
    "additional_info": "product13 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product14 of 4",
    "cost": "2000₮",
    "additional_info": "product14 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product15 of 4",
    "cost": "2000₮",
    "additional_info": "product15 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product16 of 4",
    "cost": "2000₮",
    "additional_info": "product16 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product17 of 4",
    "cost": "2000₮",
    "additional_info": "product17 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product18 of 4",
    "cost": "2000₮",
    "additional_info": "product18 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product19 of 4",
    "cost": "2000₮",
    "additional_info": "product19 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product20 of 4",
    "cost": "2000₮",
    "additional_info": "product20 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product21 of 4",
    "cost": "2000₮",
    "additional_info": "product21 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product22 of 4",
    "cost": "2000₮",
    "additional_info": "product22 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product23 of 4",
    "cost": "2000₮",
    "additional_info": "product23 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product24 of 4",
    "cost": "2000₮",
    "additional_info": "product24 of 4 additional info ",
    "unit": 5,
    "brandId": 4,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 4,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product1 of 5",
    "cost": "2000₮",
    "additional_info": "product1 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product2 of 5",
    "cost": "2000₮",
    "additional_info": "product2 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product3 of 5",
    "cost": "2000₮",
    "additional_info": "product3 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product4 of 5",
    "cost": "2000₮",
    "additional_info": "product4 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product5 of 5",
    "cost": "2000₮",
    "additional_info": "product5 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product6 of 5",
    "cost": "2000₮",
    "additional_info": "product6 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product7 of 5",
    "cost": "2000₮",
    "additional_info": "product7 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product8 of 5",
    "cost": "2000₮",
    "additional_info": "product8 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product9 of 5",
    "cost": "2000₮",
    "additional_info": "product9 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product10 of 5",
    "cost": "2000₮",
    "additional_info": "product10 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product11 of 5",
    "cost": "2000₮",
    "additional_info": "product11 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product12 of 5",
    "cost": "2000₮",
    "additional_info": "product12 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product13 of 5",
    "cost": "2000₮",
    "additional_info": "product13 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product14 of 5",
    "cost": "2000₮",
    "additional_info": "product14 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product15 of 5",
    "cost": "2000₮",
    "additional_info": "product15 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product16 of 5",
    "cost": "2000₮",
    "additional_info": "product16 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product17 of 5",
    "cost": "2000₮",
    "additional_info": "product17 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product18 of 5",
    "cost": "2000₮",
    "additional_info": "product18 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product19 of 5",
    "cost": "2000₮",
    "additional_info": "product19 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product20 of 5",
    "cost": "2000₮",
    "additional_info": "product20 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product21 of 5",
    "cost": "2000₮",
    "additional_info": "product21 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product22 of 5",
    "cost": "2000₮",
    "additional_info": "product22 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product23 of 5",
    "cost": "2000₮",
    "additional_info": "product23 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product24 of 5",
    "cost": "2000₮",
    "additional_info": "product24 of 5 additional info ",
    "unit": 5,
    "brandId": 5,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 5,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product1 of 6",
    "cost": "2000₮",
    "additional_info": "product1 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product2 of 6",
    "cost": "2000₮",
    "additional_info": "product2 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product3 of 6",
    "cost": "2000₮",
    "additional_info": "product3 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product4 of 6",
    "cost": "2000₮",
    "additional_info": "product4 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product5 of 6",
    "cost": "2000₮",
    "additional_info": "product5 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product6 of 6",
    "cost": "2000₮",
    "additional_info": "product6 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product7 of 6",
    "cost": "2000₮",
    "additional_info": "product7 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product8 of 6",
    "cost": "2000₮",
    "additional_info": "product8 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product9 of 6",
    "cost": "2000₮",
    "additional_info": "product9 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product10 of 6",
    "cost": "2000₮",
    "additional_info": "product10 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product11 of 6",
    "cost": "2000₮",
    "additional_info": "product11 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product12 of 6",
    "cost": "2000₮",
    "additional_info": "product12 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product13 of 6",
    "cost": "2000₮",
    "additional_info": "product13 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product14 of 6",
    "cost": "2000₮",
    "additional_info": "product14 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product15 of 6",
    "cost": "2000₮",
    "additional_info": "product15 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product16 of 6",
    "cost": "2000₮",
    "additional_info": "product16 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product17 of 6",
    "cost": "2000₮",
    "additional_info": "product17 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product18 of 6",
    "cost": "2000₮",
    "additional_info": "product18 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product19 of 6",
    "cost": "2000₮",
    "additional_info": "product19 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product20 of 6",
    "cost": "2000₮",
    "additional_info": "product20 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product21 of 6",
    "cost": "2000₮",
    "additional_info": "product21 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product22 of 6",
    "cost": "2000₮",
    "additional_info": "product22 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product23 of 6",
    "cost": "2000₮",
    "additional_info": "product23 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product24 of 6",
    "cost": "2000₮",
    "additional_info": "product24 of 6 additional info ",
    "unit": 5,
    "brandId": 6,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 6,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product1 of 7",
    "cost": "2000₮",
    "additional_info": "product1 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product2 of 7",
    "cost": "2000₮",
    "additional_info": "product2 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product3 of 7",
    "cost": "2000₮",
    "additional_info": "product3 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product4 of 7",
    "cost": "2000₮",
    "additional_info": "product4 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product5 of 7",
    "cost": "2000₮",
    "additional_info": "product5 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product6 of 7",
    "cost": "2000₮",
    "additional_info": "product6 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product7 of 7",
    "cost": "2000₮",
    "additional_info": "product7 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product8 of 7",
    "cost": "2000₮",
    "additional_info": "product8 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product9 of 7",
    "cost": "2000₮",
    "additional_info": "product9 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product10 of 7",
    "cost": "2000₮",
    "additional_info": "product10 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product11 of 7",
    "cost": "2000₮",
    "additional_info": "product11 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product12 of 7",
    "cost": "2000₮",
    "additional_info": "product12 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product13 of 7",
    "cost": "2000₮",
    "additional_info": "product13 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product14 of 7",
    "cost": "2000₮",
    "additional_info": "product14 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product15 of 7",
    "cost": "2000₮",
    "additional_info": "product15 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product16 of 7",
    "cost": "2000₮",
    "additional_info": "product16 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product17 of 7",
    "cost": "2000₮",
    "additional_info": "product17 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product18 of 7",
    "cost": "2000₮",
    "additional_info": "product18 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product19 of 7",
    "cost": "2000₮",
    "additional_info": "product19 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product20 of 7",
    "cost": "2000₮",
    "additional_info": "product20 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product21 of 7",
    "cost": "2000₮",
    "additional_info": "product21 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product22 of 7",
    "cost": "2000₮",
    "additional_info": "product22 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product23 of 7",
    "cost": "2000₮",
    "additional_info": "product23 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product24 of 7",
    "cost": "2000₮",
    "additional_info": "product24 of 7 additional info ",
    "unit": 5,
    "brandId": 7,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 7,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product1 of 8",
    "cost": "2000₮",
    "additional_info": "product1 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product2 of 8",
    "cost": "2000₮",
    "additional_info": "product2 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product3 of 8",
    "cost": "2000₮",
    "additional_info": "product3 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product4 of 8",
    "cost": "2000₮",
    "additional_info": "product4 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product5 of 8",
    "cost": "2000₮",
    "additional_info": "product5 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product6 of 8",
    "cost": "2000₮",
    "additional_info": "product6 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product7 of 8",
    "cost": "2000₮",
    "additional_info": "product7 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product8 of 8",
    "cost": "2000₮",
    "additional_info": "product8 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product9 of 8",
    "cost": "2000₮",
    "additional_info": "product9 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product10 of 8",
    "cost": "2000₮",
    "additional_info": "product10 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product11 of 8",
    "cost": "2000₮",
    "additional_info": "product11 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product12 of 8",
    "cost": "2000₮",
    "additional_info": "product12 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product13 of 8",
    "cost": "2000₮",
    "additional_info": "product13 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product14 of 8",
    "cost": "2000₮",
    "additional_info": "product14 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product15 of 8",
    "cost": "2000₮",
    "additional_info": "product15 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product16 of 8",
    "cost": "2000₮",
    "additional_info": "product16 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product17 of 8",
    "cost": "2000₮",
    "additional_info": "product17 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product18 of 8",
    "cost": "2000₮",
    "additional_info": "product18 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product19 of 8",
    "cost": "2000₮",
    "additional_info": "product19 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product20 of 8",
    "cost": "2000₮",
    "additional_info": "product20 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product21 of 8",
    "cost": "2000₮",
    "additional_info": "product21 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product22 of 8",
    "cost": "2000₮",
    "additional_info": "product22 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product23 of 8",
    "cost": "2000₮",
    "additional_info": "product23 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product24 of 8",
    "cost": "2000₮",
    "additional_info": "product24 of 8 additional info ",
    "unit": 5,
    "brandId": 8,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 8,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product1 of 9",
    "cost": "2000₮",
    "additional_info": "product1 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product2 of 9",
    "cost": "2000₮",
    "additional_info": "product2 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product3 of 9",
    "cost": "2000₮",
    "additional_info": "product3 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product4 of 9",
    "cost": "2000₮",
    "additional_info": "product4 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product5 of 9",
    "cost": "2000₮",
    "additional_info": "product5 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product6 of 9",
    "cost": "2000₮",
    "additional_info": "product6 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product7 of 9",
    "cost": "2000₮",
    "additional_info": "product7 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product8 of 9",
    "cost": "2000₮",
    "additional_info": "product8 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product9 of 9",
    "cost": "2000₮",
    "additional_info": "product9 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product10 of 9",
    "cost": "2000₮",
    "additional_info": "product10 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product11 of 9",
    "cost": "2000₮",
    "additional_info": "product11 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product12 of 9",
    "cost": "2000₮",
    "additional_info": "product12 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product13 of 9",
    "cost": "2000₮",
    "additional_info": "product13 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product14 of 9",
    "cost": "2000₮",
    "additional_info": "product14 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product15 of 9",
    "cost": "2000₮",
    "additional_info": "product15 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product16 of 9",
    "cost": "2000₮",
    "additional_info": "product16 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product17 of 9",
    "cost": "2000₮",
    "additional_info": "product17 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product18 of 9",
    "cost": "2000₮",
    "additional_info": "product18 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product19 of 9",
    "cost": "2000₮",
    "additional_info": "product19 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product20 of 9",
    "cost": "2000₮",
    "additional_info": "product20 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product21 of 9",
    "cost": "2000₮",
    "additional_info": "product21 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product22 of 9",
    "cost": "2000₮",
    "additional_info": "product22 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product23 of 9",
    "cost": "2000₮",
    "additional_info": "product23 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "product24 of 9",
    "cost": "2000₮",
    "additional_info": "product24 of 9 additional info ",
    "unit": 5,
    "brandId": 9,
    "unit_type": "ш",
    "filepath": "uploads/2021/9/productImage-1630895865061.png",
    "properties": "{\"өнгө\":\"ногоон\",\"размер\":\"XL\"}",
    "categoryId": 9,  
    "createdAt": new Date(),
    "updatedAt": new Date()
  }
], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Products', null, {});
  }
};
